name: GET UP

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'message'
        required: false
      issue_number:
        description: 'issue number'

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'
      
      - name: GET UP
        run: |
          echo "${{ secrets.G_T }} ${{ github.repository }} ${{ github.event.inputs.issue_number }} ${{ github.event.inputs.message }}"
          #source venv/bin/activate
          #python main.py ${{ secrets.G_T }} ${{ github.repository }} ${{ github.event.inputs.issue_number }} --message "${{ github.event.inputs.message }}"

